apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-example
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: naresh240.qis@gmail.com
    privateKeySecretRef:
      name: letsencrypt-example
    solvers:
    - http01:
        ingress:
          class: nginx